-- ==============================================================================
-- SUPABASE INITIALIZATION SCRIPT FOR DIDIER BERTRAND PORTFOLIO
-- ==============================================================================

-- 1. Create the `series` table
CREATE TABLE IF NOT EXISTS public.series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    cat TEXT DEFAULT 'Série Photographique',
    "desc" TEXT,
    cover TEXT,
    images_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on `series`
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;

-- Create policies for `series` (Public can Read, Authenticated can Create/Update/Delete)
CREATE POLICY "Public profiles are viewable by everyone." 
ON public.series FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own series." 
ON public.series FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Users can update their own series." 
ON public.series FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Users can delete their own series." 
ON public.series FOR DELETE 
TO authenticated 
USING (true);

-- 2. Setup Storage Bucket for `portfolio_images`
INSERT INTO storage.buckets (id, name, public) 
VALUES ('portfolio_images', 'portfolio_images', true)
ON CONFLICT (id) DO NOTHING;

-- Create storage policies
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'portfolio_images');

CREATE POLICY "Authenticated users can upload" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK (bucket_id = 'portfolio_images');

CREATE POLICY "Authenticated users can update" 
ON storage.objects FOR UPDATE 
TO authenticated 
USING (bucket_id = 'portfolio_images');

CREATE POLICY "Authenticated users can delete" 
ON storage.objects FOR DELETE 
TO authenticated 
USING (bucket_id = 'portfolio_images');
